[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "aiosyslog"
version = "0.1.0"
description = "Your package description here"
authors = [
    { name = "Alexander Böhm", email = "alxndr.boehm@gmail.com" },
    { name = "Ilya Tovbin", email = "itovbin@fortinet.com" }
]
license = { text = "BSD-2-Clause" }
readme = "README.md"
requires-python = ">=3.9"

[tool.setuptools]
packages = ["aiosyslog"]
